### ISSUE TITLE
Max combo config param

### ISSUE THREAD

**Issue by Glideh** [Glideh/cs-gvg-teams#2]
For now a skill just can't be found twice in a team.
In the skill config, add a maximum number of time it can be found in a team.
Example:

```yml
cleanse:
  label: "Cleanses weakening effects"
  power: 2
  max_combo: 2
```

Here a cleanse could be found 2 times max in a team
